config/routes.rb
Rails.application.routes.draw do
  resources :campaigns do
    get :display_banner, on: :member
    get :html_code, on: :member

    resources :banners, except: [:index, :show, :new] do
      get :click, on: :member
    end
  end

  root to: 'campaigns#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner.rb
class Banner < ApplicationRecord
  mount_uploader :image, BannerImageUploader

  belongs_to :campaign
  has_many :page_visits, dependent: :destroy

  validates :landing_page, format: { with: URI::regexp(%w(http https)), allow_blank: true }
  validates_presence_of :image

  delegate :landing_page, to: :campaign, allow_nil: true, prefix: true

  def current_landing_page
    self.landing_page.presence || self.campaign_landing_page
  end
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :banners, dependent: :destroy
  has_many :page_visits, through: :banners

  validates :title, presence: true, uniqueness: true
  validates :landing_page,
    presence: true,
    format: { with: URI::regexp(%w(http https)), allow_blank: true }

  def self.banner_weights_sum
    Campaign.joins(:banners).group(:id).sum(:percentage_of_shows)
  end

  def weights_sum_correct?
    self.class.banner_weights_sum[self.id] == 100
  end

  def load_banners
    self.banners.all.load
  end

  def campaign_aggregated_data
    unique_users_relation = self.page_visits.group(:banner_id).distinct(:source_ip)
    most_visited_domain_relation = self.page_visits.group(:source_domain)

    {
      unique_users_clicked: unique_users_relation.where('clicks_count > 0').count(:source_ip),
      unique_users_viewed: unique_users_relation.where('views_count > 0').count(:source_ip),
      most_clicked_domain: most_visited_domain_relation.maximum(:clicks_count).max_by{ |_, v| v }.try(:first),
      most_viewed_domain: most_visited_domain_relation.maximum(:views_count).max_by{ |_, v| v }.try(:first)
    }
  end
end

app/models/page_visit.rb
class PageVisit < ApplicationRecord
  belongs_to :banner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/banners_controller.rb
class BannersController < ApplicationController
  before_action :set_campaign
  before_action :set_banner, except: [:new, :create]

  def new
    @banner = @campaign.banners.new
  end

  def edit
  end

  def create
    @banner = @campaign.banners.new(banner_params)
    @banners = @campaign.load_banners
    @campaign_aggregated_data = @campaign.campaign_aggregated_data

    if @banner.save
      redirect_to @campaign, notice: 'Banner was successfully created.'
    else
      render 'campaigns/show'
    end
  end

  def update
    if @banner.update(banner_params)
      redirect_to @campaign, notice: 'Banner was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @banner.destroy
    redirect_to @campaign, notice: 'Banner was successfully destroyed.'
  end

  def click
    @page_visit = ClickBanner.new(@banner, request.remote_ip, request.referer).perform

    redirect_to @banner.current_landing_page
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:campaign_id])
    end

    def set_banner
      @banner = @campaign.banners.find(params[:id])
    end

    def banner_params
      params.require(:banner).permit(:percentage_of_shows, :landing_page, :image)
    end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, except: [:index, :new, :create]

  def index
    @campaigns = Campaign.order(:title).load
    @weights_sum = Campaign.banner_weights_sum
  end

  def show
    @banners = @campaign.load_banners
    @campaign_aggregated_data = @campaign.campaign_aggregated_data

    @banner = @campaign.banners.new

    flash.now[:error] = "Total weights sum of all banners must equal 100" unless @campaign.weights_sum_correct?
  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      redirect_to campaigns_path, notice: 'Campaign was successfully created.'
    else
      render :new
    end
  end

  def update
    if @campaign.update(campaign_params)
      redirect_to campaigns_path, notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_path, notice: 'Campaign was successfully destroyed.'
  end

  def display_banner
    @banner = FindRandomBanner.new(@campaign).perform
    @page_visit = ViewBanner.new(@banner, request.remote_ip, request.referer).perform

    render layout: false
  end

  def html_code
    render layout: false
  end

  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:title, :landing_page, :html_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_errors.html.haml
-if record.errors.any?
  .alert.alert-danger.alert-dismissable{ role: "alert" }
    %button.close{ type: "button", data: { dismiss: "alert" } }
      %span{aria: { hidden: "true" } } &times;
      %span.sr-only Close
    %h4= "#{pluralize(record.errors.count, "error")} prohibited this banner from being saved:"
    %ul
      - record.errors.full_messages.each do |msg|
        %li= msg

app/views/banners/_form.html.haml
= form_for [@campaign, @banner], html: { class: 'form-horizontal', role: 'form', multipart: true } do |f|
  = render 'form_errors', { record: @banner }

  .form-group
    = f.label :percentage_of_shows, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :percentage_of_shows, class: 'form-control'

  .form-group
    = f.label :landing_page, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :landing_page, class: 'form-control'

  .form-group
    = f.label :image, class: 'col-sm-2 control-label'
    .col-sm-10
      = image_tag(@banner.image_url) if @banner.image?
      = f.file_field :image, class: 'form-control'
      = f.hidden_field :image_cache


  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/banners/edit.html.haml
.page-header
  = link_to @campaign, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 Editing banner

= render 'form'

app/views/campaigns/_form.html.haml
= form_for @campaign, html: { class: 'form-horizontal', role: 'form' } do |f|
  = render 'form_errors', { record: @campaign }

  .form-group
    = f.label :title, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, class: 'form-control'

  .form-group
    = f.label :landing_page, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :landing_page, class: 'form-control'

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/campaigns/display_banner.html.haml
= link_to click_campaign_banner_url(@banner.campaign, @banner), target: :_blank do
  = image_tag(@banner.image_url, style: "width:100%; max-width:300px;")

app/views/campaigns/edit.html.haml
.page-header
  .row
    .col-sm-1
      = link_to campaigns_path, class: 'btn btn-default' do
        %span.glyphicon.glyphicon-list-alt
        Back
    .col-sm-1
      = link_to @campaign, class: 'btn btn-primary' do
        %span.glyphicon.glyphicon-info-sign
        Show
    .col-sm-10

  %h1 Editing campaign

= render 'form'

app/views/campaigns/html_code.html.haml
:javascript
  var request = new XMLHttpRequest();
  request.open('GET', '#{display_banner_campaign_url(@campaign)}', true);

  request.onload = function() {
    if (request.status >= 200 && request.status < 400) {
      document.getElementsByClassName('banner-content')[0].innerHTML = request.responseText;
    } else {
      console.log('Could not load banner data')
    }
  };

  request.send();

%div.banner-content

app/views/campaigns/index.html.haml
.page-header
  = link_to new_campaign_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New campaign
  %h1 Campaigns

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th #
        %th Title
        %th Landing Page
        %th Weights sum
        %th
        %th

    %tbody
      - @campaigns.each do |campaign|
        %tr{ class: (:danger unless campaign.weights_sum_correct?) }
          %td= campaign.id
          %td= link_to campaign.title, campaign
          %td= link_to campaign.landing_page, campaign.landing_page
          %td= @weights_sum[campaign.id]
          %td= link_to '', [:edit, campaign], class: 'glyphicon glyphicon-edit'
          %td= link_to '', campaign, data: { method: :delete, confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-remove'

app/views/campaigns/new.html.haml
.page-header
  = link_to campaigns_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New campaign

= render 'form'

app/views/campaigns/show.html.haml
.page-header
  .row
    .col-sm-1
      = link_to campaigns_path, class: 'btn btn-default' do
        %span.glyphicon.glyphicon-list-alt
        Back
    .col-sm-1
      = link_to edit_campaign_path(@campaign), class: 'btn btn-primary' do
        %span.glyphicon.glyphicon-pencil
        Edit
    .col-sm-10

  %h1 Campaign details

%dl.dl-horizontal
  %dt Title
  %dd= @campaign.title

  %dt Landing Page
  %dd= link_to @campaign.landing_page, @campaign

  %dt Most clicked domain
  %dd= @campaign_aggregated_data[:most_clicked_domain]

  %dt Most viewed domain
  %dd= @campaign_aggregated_data[:most_viewed_domain]

  %dt HTML code
  %dd
    %pre.hidden
    = link_to 'Show', [:html_code, @campaign], class: 'show-banner-html-code', data: { remote: true }

.page-header
  %h3 Banners

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th #
        %th Banner Image
        %th Banner details
        %th

    %tbody
      - @banners.each do |banner|
        %tr
          %td= banner.id
          %td= image_tag(banner.image_url, class: 'img-responsive') if banner.image?
          %td
            %dl.dl-horizontal
              %dt Percentage of shows
              %dd= number_to_percentage(banner.percentage_of_shows, precision: 0)

              %dt Banner LP
              %dd= link_to banner.landing_page, banner.landing_page

              %dt Default/current LP
              %dd= link_to banner.current_landing_page, banner.current_landing_page

              %dt Unique users clicked
              %dd= @campaign_aggregated_data[:unique_users_clicked][banner.id]

              %dt Unique users viewed
              %dd= @campaign_aggregated_data[:unique_users_viewed][banner.id]

          %td
            = link_to '', [:edit, @campaign,  banner], class: 'glyphicon glyphicon-edit'
            = link_to '', [@campaign, banner], data: { method: :delete, confirm: 'Are you sure?' }, class: 'glyphicon glyphicon-remove'

.page-header
  %h3 New banner

= render 'banners/form'

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        =# 'Linklf '

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Adv Campaign'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Adv Campaign'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .container
      %header
        = render 'layouts/navigation'
      %main{:role => "main"}
        = render 'layouts/messages'
        = yield